#!/usr/bin/env bun
/**
 * Generate schema/config.json from the real config type.
 *
 * The schema is what gives editors autocomplete and validation for exa.json,
 * so it must never drift from the code — it is derived from ConfigV1.Info
 * rather than hand-written, and regenerated by `bun run schema` (CI checks it
 * is up to date).
 */
import path from "path"
import { Schema } from "effect"
import { ConfigV1 } from "@exa/core/v1/config/config"

const ROOT = path.resolve(import.meta.dirname, "../../..")
const OUT = path.join(ROOT, "schema", "config.json")

const doc = Schema.toJsonSchemaDocument(ConfigV1.Info) as unknown as {
  dialect: string
  schema: Record<string, unknown>
  definitions: Record<string, unknown>
}

// JSON Schema wants $schema/$defs at the document root; effect returns the
// dialect and definitions separately.
const dialect = doc.dialect === "draft-2020-12" ? "https://json-schema.org/draft/2020-12/schema" : doc.dialect

const output = {
  $schema: dialect,
  $id: "https://raw.githubusercontent.com/Sheetaldharshan200/exa-engine/main/schema/config.json",
  title: "exa configuration",
  description: "Configuration for the exa CLI and engine (exa.json / exa.jsonc).",
  ...doc.schema,
  $defs: doc.definitions,
}

await Bun.write(OUT, JSON.stringify(output, null, 2) + "\n")
const count = Object.keys((doc.definitions?.["Config"] as { properties?: object })?.properties ?? {}).length
console.log(`wrote ${path.relative(ROOT, OUT)} (${count} top-level keys, ${Object.keys(doc.definitions).length} definitions)`)
